Models/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Race_Track.Models
{
    public class Vehiculo
    {
        public int VehiculoId { get; set; }

        [Display(Name = "Nombre Propietario")]
        public string? VehiculoNombre {get; set;}
        
        [Display(Name = "Apellido Propietario")]
        public string? VehiculoApellido {get; set;}

        [Display(Name = "Tipo de vehiculo")]
        public string? VehiculoTipo {get; set;}

        [Display(Name = "Matricula")]
        public string? VehiculoMatricula {get; set;}

        [Display(Name = "Modelo")]
        public DateTime VehiculoFabricacion {get;set;}  
        // public int AeronaveCosto {get; set;}

        public ICollection<Piloto> PilotoList { get; set; } = new List<Piloto>();      
    }
}

Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Race_Track.Data;
using Race_Track.Models;
using Race_Track.ViewModels;

namespace Race_Track.Controllers
{
    public class VehiculoController : Controller
    {
        private readonly VehiculoContext _context;

        public VehiculoController(VehiculoContext context)
        {
            _context = context;
        }

        // GET: Vehiculo
        public async Task<IActionResult> Index(string nameFilter , VehiculoIndexViewModel vehiculoView)
        {
            var query = from vehiculo in _context.Vehiculo select vehiculo;

            if (!string.IsNullOrEmpty(nameFilter))
            {
                query = query.Where(x => x.VehiculoNombre.Contains(nameFilter) || x.VehiculoApellido.Contains(nameFilter) || x.VehiculoMatricula.Contains(nameFilter));
                // query = query.Where(x => x.VehiculoNombre.Contains(nameFilter));
            }

            var model = new VehiculoIndexViewModel();
            model.vehiculos =await query.ToListAsync();
            
            return _context.Vehiculo != null ?
            View(model):
            Problem("Entity set 'AeronaveContex.Aeronave' is null.");
        }

        // GET: Vehiculo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehiculo == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculo
                .FirstOrDefaultAsync(m => m.VehiculoId == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // GET: Vehiculo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehiculo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VehiculoId,VehiculoNombre,VehiculoApellido,VehiculoTipo,VehiculoMatricula,VehiculoFabricacion")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehiculo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehiculo);
        }

        // GET: Vehiculo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehiculo == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculo.FindAsync(id);
            if (vehiculo == null)
            {
                return NotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VehiculoId,VehiculoNombre,VehiculoApellido,VehiculoTipo,VehiculoMatricula,VehiculoFabricacion")] Vehiculo vehiculo)
        {
            if (id != vehiculo.VehiculoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculoExists(vehiculo.VehiculoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehiculo);
        }

        // GET: Vehiculo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehiculo == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculo
                .FirstOrDefaultAsync(m => m.VehiculoId == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehiculo == null)
            {
                return Problem("Entity set 'VehiculoContext.Vehiculo'  is null.");
            }
            var vehiculo = await _context.Vehiculo.FindAsync(id);
            if (vehiculo != null)
            {
                _context.Vehiculo.Remove(vehiculo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculoExists(int id)
        {
          return (_context.Vehiculo?.Any(e => e.VehiculoId == id)).GetValueOrDefault();
        }
    }
}

Views/Vehiculo/Create.cshtml
@model Race_Track.Models.Vehiculo
@* @using Race_Track.ViewModels; *@
@* @model VehiculoIndexViewModel; *@

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Vehiculo</h1>
<br> 
<h4>Datos del Vehiculo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <br> 
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="VehiculoNombre" class="control-label"></label>
                <input asp-for="VehiculoNombre" class="form-control" />
                <span asp-validation-for="VehiculoNombre" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoApellido" class="control-label"></label>
                <input asp-for="VehiculoApellido" class="form-control" />
                <span asp-validation-for="VehiculoApellido" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoTipo" class="control-label"></label>
                <input asp-for="VehiculoTipo" class="form-control" />
                <span asp-validation-for="VehiculoTipo" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoMatricula" class="control-label"></label>
                <input asp-for="VehiculoMatricula" class="form-control" />
                <span asp-validation-for="VehiculoMatricula" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoFabricacion" class="control-label"></label>
                <input asp-for="VehiculoFabricacion" class="form-control" />
                <span asp-validation-for="VehiculoFabricacion" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
            <br> 
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Vehiculo/Delete.cshtml
@model Race_Track.Models.Vehiculo

@{
    ViewData["Title"] = "Delete";
}

<h3>Datos del vehiculo a eliminar:</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoTipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoTipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoMatricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoMatricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoFabricacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoFabricacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VehiculoId" />
        <input type="submit" value="Eliminar Vehiculo" class="btn btn-danger" /> 
        <br>
        <br>
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Vehiculo/Details.cshtml
@model Race_Track.Models.Vehiculo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del vehiculo</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoTipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoTipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoMatricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoMatricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiculoFabricacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiculoFabricacion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Volver</a>
</div>

Views/Vehiculo/Edit.cshtml
@model Race_Track.Models.Vehiculo

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Vehiculo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VehiculoId" />
            <div class="form-group">
                <label asp-for="VehiculoNombre" class="control-label"></label>
                <input asp-for="VehiculoNombre" class="form-control" />
                <span asp-validation-for="VehiculoNombre" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoApellido" class="control-label"></label>
                <input asp-for="VehiculoApellido" class="form-control" />
                <span asp-validation-for="VehiculoApellido" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoTipo" class="control-label"></label>
                <input asp-for="VehiculoTipo" class="form-control" />
                <span asp-validation-for="VehiculoTipo" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoMatricula" class="control-label"></label>
                <input asp-for="VehiculoMatricula" class="form-control" />
                <span asp-validation-for="VehiculoMatricula" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <label asp-for="VehiculoFabricacion" class="control-label"></label>
                <input asp-for="VehiculoFabricacion" class="form-control" />
                <span asp-validation-for="VehiculoFabricacion" class="text-danger"></span>
            </div>
            <br> 
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-success" />             
                </div>
            <br> 
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Vehiculo/Index.cshtml
@* @model IEnumerable<Race_Track.Models.Vehiculo> *@
@using Race_Track.ViewModels;
@model VehiculoIndexViewModel;

@{
    ViewData["Title"] = "Index";
}

<h1>Vehiculos</h1>

<p>
    <a asp-action="Create" class="btn btn-success">+ Vehiculo</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Vehiculo">
        <div class="col-6 form-group">
            <input class="form-control" asp-for="NameFilter"/>
        </div>
        <br>
        <button class="btn btn-info" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoApellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoTipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoMatricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoFabricacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.vehiculos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VehiculoNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehiculoApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehiculoTipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehiculoMatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehiculoFabricacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VehiculoId"class="btn btn-warning">Modificar</a> 
                <a asp-action="Details" asp-route-id="@item.VehiculoId" class="btn btn-primary">Detalle</a> 
                <a asp-action="Delete" asp-route-id="@item.VehiculoId"  class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar este instructor?')">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>