Models/Piloto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace Race_Track.Models
{
    public class Piloto
    {
        public int PilotoId { get; set; }

        [Display(Name = "Nombre")]        
        public string? PilotoNombre {get; set;}
        
        [Display(Name = "Apellido")]        
        public string? PilotoApellido {get; set;}
        
        [Display(Name = "Dni")]        
        public int PilotoDni {get; set;}
        // public LicenciaType InstructorTipoLicencia { get; set; }
        [Display(Name = "Numero registro")]        
        public int PilotoNumeroLicencia {get; set;}
        [Display(Name = "Fecha de vencimiento")]        
        public DateTime PilotoExpedicion {get;set;}
        
        [Display(Name = "Es propietario?")]        
        public bool PilotoPropietario {get;set;} = true;       
        
        [Display(Name = "Vehiculo asignado")]
        public int VehiculoId { get; set; }          
        public virtual Vehiculo? Vehiculo { get; set; }        
    }
}

Controllers/PilotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Race_Track.Data;
using Race_Track.Models;
using Race_Track.ViewModels;

namespace Race_Track.Controllers
{
    public class PilotoController : Controller
    {
        private readonly VehiculoContext _context;

        public PilotoController(VehiculoContext context)
        {
            _context = context;
        }

        // GET: Piloto
        // public async Task<IActionResult> Index(string nameFilter , PilotoIndexViewModel pilotoView)
        public async Task<IActionResult> Index(string nameFilter)
        {
            var query = from piloto in _context.Piloto.Include(i => i.Vehiculo) select piloto;

            if (!string.IsNullOrEmpty(nameFilter))
            {
                query = query.Where(x => x.PilotoNombre.Contains(nameFilter) || x.PilotoApellido.Contains(nameFilter) || x.PilotoDni.ToString() == nameFilter);
            }

            var model = new PilotoIndexViewModel();
            model.pilotos =await query.ToListAsync();

            return _context.Piloto != null ?
            View(model):
            Problem("Entity set 'AeronaveContex.Aeronave' is null.");

        }

        // GET: Piloto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Piloto == null)
            {
                return NotFound();
            }

            var piloto = await _context.Piloto
                .Include(p => p.Vehiculo)
                .FirstOrDefaultAsync(m => m.PilotoId == id);
            if (piloto == null)
            {
                return NotFound();
            }

            return View(piloto);
        }

        // GET: Piloto/Create
        public IActionResult Create()
        {
            ViewData["VehiculoId"] = new SelectList(_context.Vehiculo, "VehiculoId", "VehiculoTipo");
            return View();
        }

        // POST: Piloto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PilotoId,PilotoNombre,PilotoApellido,PilotoDni,PilotoNumeroLicencia,PilotoExpedicion,PilotoPropietario,VehiculoId")] Piloto piloto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(piloto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VehiculoId"] = new SelectList(_context.Vehiculo, "VehiculoId", "VehiculoId", piloto.VehiculoId);
            return View(piloto);
        }

        // GET: Piloto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Piloto == null)
            {
                return NotFound();
            }

            var piloto = await _context.Piloto.FindAsync(id);
            if (piloto == null)
            {
                return NotFound();
            }
            // ViewData["VehiculoId"] = new SelectList(_context.Vehiculo, "VehiculoTipo", "VehiculoTipo", piloto.VehiculoId);
            ViewData["VehiculoId"] = new SelectList(_context.Vehiculo, "VehiculoId", "VehiculoTipo");
            return View(piloto);
        }

        // POST: Piloto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PilotoId,PilotoNombre,PilotoApellido,PilotoDni,PilotoNumeroLicencia,PilotoExpedicion,PilotoPropietario,VehiculoId")] Piloto piloto)
        {
            if (id != piloto.PilotoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(piloto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PilotoExists(piloto.PilotoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VehiculoId"] = new SelectList(_context.Vehiculo, "VehiculoId", "VehiculoId", piloto.VehiculoId);
            return View(piloto);
        }

        // GET: Piloto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Piloto == null)
            {
                return NotFound();
            }

            var piloto = await _context.Piloto
                .Include(p => p.Vehiculo)
                .FirstOrDefaultAsync(m => m.PilotoId == id);
            if (piloto == null)
            {
                return NotFound();
            }

            return View(piloto);
        }

        // POST: Piloto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Piloto == null)
            {
                return Problem("Entity set 'VehiculoContext.Piloto'  is null.");
            }
            var piloto = await _context.Piloto.FindAsync(id);
            if (piloto != null)
            {
                _context.Piloto.Remove(piloto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PilotoExists(int id)
        {
          return (_context.Piloto?.Any(e => e.PilotoId == id)).GetValueOrDefault();
        }
    }
}

Views/Piloto/Create.cshtml
@model Race_Track.Models.Piloto

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Piloto</h1>

<h4>Datos del Piloto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PilotoNombre" class="control-label"></label>
                <input asp-for="PilotoNombre" class="form-control" />
                <span asp-validation-for="PilotoNombre" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoApellido" class="control-label"></label>
                <input asp-for="PilotoApellido" class="form-control" />
                <span asp-validation-for="PilotoApellido" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoDni" class="control-label"></label>
                <input asp-for="PilotoDni" class="form-control" />
                <span asp-validation-for="PilotoDni" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoNumeroLicencia" class="control-label"></label>
                <input asp-for="PilotoNumeroLicencia" class="form-control" />
                <span asp-validation-for="PilotoNumeroLicencia" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoExpedicion" class="control-label"></label>
                <input asp-for="PilotoExpedicion" class="form-control" />
                <span asp-validation-for="PilotoExpedicion" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PilotoPropietario" /> @Html.DisplayNameFor(model => model.PilotoPropietario)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="VehiculoId" class="control-label"></label>
                <select asp-for="VehiculoId" class ="form-control" asp-items="ViewBag.VehiculoId"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Piloto/Delete.cshtml
@model Race_Track.Models.Piloto

@{
    ViewData["Title"] = "Delete";
}

<h3>Datos del piloto a eliminar:</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoDni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoDni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoNumeroLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoNumeroLicencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoExpedicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoExpedicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoPropietario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoPropietario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vehiculo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vehiculo.VehiculoTipo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PilotoId" />
        <input type="submit" value="Eliminar Piloto" class="btn btn-danger" /> 
        <br>
        <br>
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Piloto/Details.cshtml
@model Race_Track.Models.Piloto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del Piloto</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoDni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoDni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoNumeroLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoNumeroLicencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoExpedicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoExpedicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotoPropietario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotoPropietario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vehiculo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vehiculo.VehiculoTipo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Volver</a>
</div>

Views/Piloto/Edit.cshtml
@model Race_Track.Models.Piloto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Piloto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PilotoId" />
            <div class="form-group">
                <label asp-for="PilotoNombre" class="control-label"></label>
                <input asp-for="PilotoNombre" class="form-control" />
                <span asp-validation-for="PilotoNombre" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoApellido" class="control-label"></label>
                <input asp-for="PilotoApellido" class="form-control" />
                <span asp-validation-for="PilotoApellido" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoDni" class="control-label"></label>
                <input asp-for="PilotoDni" class="form-control" />
                <span asp-validation-for="PilotoDni" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoNumeroLicencia" class="control-label"></label>
                <input asp-for="PilotoNumeroLicencia" class="form-control" />
                <span asp-validation-for="PilotoNumeroLicencia" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="PilotoExpedicion" class="control-label"></label>
                <input asp-for="PilotoExpedicion" class="form-control" />
                <span asp-validation-for="PilotoExpedicion" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PilotoPropietario" /> @Html.DisplayNameFor(model => model.PilotoPropietario)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="VehiculoId" class="control-label"></label>
                <select asp-for="VehiculoId" class="form-control" asp-items="ViewBag.VehiculoId"></select>
                @* <span asp-validation-for="VehiculoId" class="text-danger"></span> *@
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-success" />             
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Piloto/Index.cshtml
@* @model IEnumerable<Race_Track.Models.Piloto> *@
@using Race_Track.ViewModels;
@model PilotoIndexViewModel;

@{
    ViewData["Title"] = "Index";
}

<h1>Pilotos</h1>

<p>
    <a asp-action="Create" class="btn btn-success">+ Piloto</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Piloto">
        <div class="col-6 form-group">
            <input class="form-control" asp-for="NameFilter"/>
        </div>
        <br>
        <button class="btn btn-info" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PilotoNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotoApellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotoDni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotoNumeroLicencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotoExpedicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotoPropietario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehiculo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.pilotos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoDni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoNumeroLicencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoExpedicion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PilotoPropietario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vehiculo.VehiculoTipo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PilotoId"class="btn btn-warning">Modificar</a> 
                <a asp-action="Details" asp-route-id="@item.PilotoId" class="btn btn-primary">Detalle</a> 
                <a asp-action="Delete" asp-route-id="@item.PilotoId"  class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar este instructor?')">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>